apiVersion: apps/v1                          # API version for the StatefulSet
kind: StatefulSet                            # Type of Kubernetes object being defined
metadata:                                   
  name: es-cluster                           # Name of the StatefulSet
  namespace: kube-logging                    # Namespace where the StatefulSet is deployed
spec:                                        
  serviceName: elasticsearch                 # Service name that the pods will use to communicate with each other
  replicas: 3                                # Number of pod replicas in the StatefulSet
  selector:                                  
    matchLabels:                             
      app: elasticsearch                     # Label selector to identify which pods belong to this StatefulSet
  template:                                  
    metadata:                                
      labels:                                
        app: elasticsearch                   # Labels to be applied to all pods in the StatefulSet
    spec:                                    
      containers:                            
      - name: elasticsearch                  # Container name
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0 # Container image
        resources:                           # Resource requests and limits for the container
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
        ports:                               # Ports that the container exposes
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        volumeMounts:                        # Mount paths for volumes inside the container
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:                                 # Environment variables for the container
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "es-cluster-0.elasticsearch,es-cluster-1.elasticsearch,es-cluster-2.elasticsearch"
          - name: cluster.initial_master_nodes
            value: "es-cluster-0,es-cluster-1,es-cluster-2"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:                        # Containers that run before the main container to prepare the environment
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
  volumeClaimTemplates:                      # Template for PersistentVolumeClaims that the pods in this StatefulSet will use
  - metadata:
      name: data
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]       # Access mode for the volume
      storageClassName: managed-premium      # StorageClass for the volume
      resources:
        requests:
          storage: 10Gi                      # Amount of storage requested for each volume
